# Generated by Django 5.0.6 on 2024-05-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='Username')),
                ('email', models.EmailField(max_length=125, unique=True, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, verbose_name='User is active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='User is staff')),
                ('is_admin', models.BooleanField(default=False, verbose_name='User is superuser (is have admin status)')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users`s',
                'db_table': 'user_table',
                'db_table_comment': 'the table responsible for storing user models',
            },
        ),
    ]
